<a href="https://colab.research.google.com/github/sdasmaha/Ml_Engineers_445/blob/master/ML4IOT_COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
!pip install dtw

  Created wheel for dtw: filename=dtw-1.4.0-cp36-none-any.whl size=5315 sha256=0ef0785fce1ba184db87ae7832db212120fea457408a6baf3653294fe4e54579
  Stored in directory: /root/.cache/pip/wheels/8c/8b/7a/947d67b53cd54948890a173527b0470ef56998812fc9d0a803
Successfully built dtw


In [3]:
from dtw import dtw 

In [4]:
from google.colab import drive
drive.mount("/content/gdrive")

Mounted at /content/gdrive


#Loading the Datasets

*Jump*

In [5]:
df_acc_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_chest.csv")
df_acc_jump_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_forearm.csv")
df_acc_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_head.csv")
df_acc_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_shin.csv")
df_acc_jump_thigh= pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_thigh.csv")
df_acc_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_upperarm.csv")
df_acc_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/acc_jumping_csv/acc_jumping_waist.csv")
df_gps_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_chest.csv")
df_gps_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_head.csv")
df_gps_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_shin.csv")
df_gps_jump_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_thigh.csv")
df_gps_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_upperarm.csv")
df_gps_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gps_jumping_csv/GPS_jumping_waist.csv")
df_gyr_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_chest.csv")
df_gyr_jump_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_forearm.csv")
df_gyr_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_head.csv")
df_gyr_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_shin.csv")
df_gyr_jump_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_thigh.csv")
df_gyr_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_upperarm.csv")
df_gyr_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/gyr_jumping_csv/Gyroscope_jumping_waist.csv")
df_lig_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_chest.csv")
df_lig_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_head.csv")
df_lig_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_shin.csv")
df_lig_jump_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_thigh.csv")
df_lig_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_upperarm.csv")
df_lig_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/lig_jumping_csv/Light_jumping_waist.csv")
df_mag_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_chest.csv")
df_mag_jump_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_forearm.csv")
df_mag_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_head.csv")
df_mag_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_shin.csv")
df_mag_jump_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_thigh.csv")
df_mag_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_upperarm.csv")
df_mag_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mag_jumping_csv/MagneticField_jumping_waist.csv")
df_mic_jump_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_chest.csv")
df_mic_jump_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_head.csv")
df_mic_jump_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_shin.csv")
df_mic_jump_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_thigh.csv")
df_mic_jump_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_upperarm.csv")
df_mic_jump_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Jumping/mic_jumping_csv/Microphone_jumping_waist.csv")

*Lying*

In [6]:
df_acc_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_chest.csv")
df_acc_lye_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_forearm.csv")
df_acc_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_head.csv")
df_acc_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_shin.csv")
df_acc_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_thigh.csv")
df_acc_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_upperarm.csv")
df_acc_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/acc_lying_csv/acc_lying_waist.csv") 
df_gps_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_chest.csv")
df_gps_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_head.csv")
df_gps_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_shin.csv")
df_gps_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_thigh.csv")
df_gps_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_upperarm.csv")
df_gps_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gps_lying_csv/GPS_lying_waist.csv")
df_gyr_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_chest.csv")
df_gyr_lye_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_forearm.csv")
df_gyr_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_head.csv")
df_gyr_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_shin.csv")
df_gyr_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_thigh.csv")
df_gyr_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_upperarm.csv")
df_gyr_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/gyr_lying_csv/Gyroscope_lying_waist.csv")
df_lig_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_chest.csv")
df_lig_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_head.csv")
df_lig_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_shin.csv")
df_lig_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_thigh.csv")
df_lig_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_upperarm.csv")
df_lig_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/lig_lying_csv/Light_lying_waist.csv")
 
df_mag_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_chest.csv")
df_mag_lye_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_forearm.csv")
df_mag_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_head.csv")
df_mag_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_shin.csv")
df_mag_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_thigh.csv")
df_mag_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_upperarm.csv")
df_mag_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mag_lying_csv/MagneticField_lying_waist.csv")
 
df_mic_lye_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_chest.csv")
df_mic_lye_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_head.csv")
df_mic_lye_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_shin.csv")
df_mic_lye_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_thigh.csv")
df_mic_lye_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_upperarm.csv")
df_mic_lye_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Lying/mic_lying_csv/Microphone_lying_waist.csv")

*Stand*

In [7]:
df_acc_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_chest.csv")
df_acc_stand_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_forearm.csv")
df_acc_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_head.csv")
df_acc_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_shin.csv")
df_acc_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_upperarm.csv")
df_acc_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_upperarm.csv")
df_acc_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/acc_standing_csv/acc_standing_waist.csv")
 
df_gps_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_chest.csv")
df_gps_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_head.csv")
df_gps_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_shin.csv")
df_gps_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_thigh.csv")
df_gps_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_upperarm.csv")
df_gps_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gps_standing_csv/GPS_standing_waist.csv")
 
df_gyr_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_chest.csv")
df_gyr_stand_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_forearm.csv")
df_gyr_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_head.csv")
df_gyr_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_shin.csv")
df_gyr_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_thigh.csv")
df_gyr_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_upperarm.csv")
df_gyr_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/gyr_standing_csv/Gyroscope_standing_waist.csv")

df_lig_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_chest.csv")
df_lig_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_head.csv")
df_lig_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_shin.csv")
df_lig_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_thigh.csv")
df_lig_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_upperarm.csv")
df_lig_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/lig_standing_csv/Light_standing_waist.csv")

df_mag_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_chest.csv")
df_mag_stand_forearm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_forearm.csv")
df_mag_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_head.csv")
df_mag_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_shin.csv")
df_mag_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_thigh.csv")
df_mag_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_upperarm.csv")
df_mag_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mag_standing_csv/MagneticField_standing_waist.csv")

df_mic_stand_chest = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_chest.csv")
df_mic_stand_head = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_head.csv")
df_mic_stand_shin = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_shin.csv")
df_mic_stand_thigh = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_thigh.csv")
df_mic_stand_upperarm = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_upperarm.csv")
df_mic_stand_waist = pd.read_csv("/content/gdrive/My Drive/ML4IOT/Notebook 1/Standing/mic_standing_csv/Microphone_standing_waist.csv")

#Acceloremeter

In [8]:
df_acc_jump_chest = df_acc_jump_chest[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_forearm = df_acc_jump_forearm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_head = df_acc_jump_head[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_shin = df_acc_jump_shin[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_thigh = df_acc_jump_thigh[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_upperarm = df_acc_jump_upperarm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_jump_waist = df_acc_jump_waist[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_chest = df_acc_lye_chest[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_forearm = df_acc_lye_forearm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_head = df_acc_lye_head[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_shin = df_acc_lye_shin[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_thigh = df_acc_lye_thigh[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_upperarm = df_acc_lye_upperarm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_lye_waist = df_acc_lye_waist[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_chest = df_acc_stand_chest[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_forearm = df_acc_stand_forearm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_head = df_acc_stand_head[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_shin = df_acc_stand_shin[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_thigh = df_acc_stand_thigh[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_upperarm = df_acc_stand_upperarm[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]
df_acc_stand_waist = df_acc_stand_waist[['attr_x', 'attr_y', 'attr_z']].values[0:999,:]



In [9]:
acc_jump = [df_acc_jump_chest,df_acc_jump_forearm,df_acc_jump_head,df_acc_jump_shin,df_acc_jump_thigh,df_acc_jump_upperarm,df_acc_jump_waist]
acc_lye = [df_acc_lye_chest,df_acc_lye_forearm ,df_acc_lye_head,df_acc_lye_shin,df_acc_lye_thigh,df_acc_lye_upperarm,df_acc_lye_waist]
acc_stand = [df_acc_stand_chest,df_acc_stand_forearm ,df_acc_stand_head,df_acc_stand_shin,df_acc_stand_thigh,df_acc_stand_upperarm,df_acc_stand_waist]

In [ ]:
acc_jump = [df_acc_jump_chest,df_acc_jump_forearm,df_acc_jump_head,df_acc_jump_shin,df_acc_jump_thigh,df_acc_jump_upperarm,df_acc_jump_waist]

In [ ]:
acc_lye = [df_acc_lye_chest,df_acc_lye_forearm ,df_acc_lye_head,df_acc_lye_shin,df_acc_lye_thigh,df_acc_lye_upperarm,df_acc_lye_waist]

In [ ]:
acc_stand = [df_acc_stand_chest,df_acc_stand_forearm ,df_acc_stand_head,df_acc_stand_shin,df_acc_stand_thigh,df_acc_stand_upperarm,df_acc_stand_waist]

In [ ]:
results = []
for i in acc_jump:
  for j in acc_jump:
    euclidean_distance =  lambda i,j: np.linalg.norm(i-j)
    d, cost_matrix, acc_cost_matrix, path = dtw(i, j, dist = euclidean_distance)
    results.append(d)

np.hstack(results)

array([    0.        , 14829.15491897, 12986.42782376,  7708.46421049,
        4076.84240386,  3977.11243373, 13250.36862331, 10983.17121063,
       14892.54574511, 14299.77810531, 10760.00334833, 11289.04306081,
       10722.38032688, 14520.56983296, 14829.15491897,     0.        ,
           0.        , 14829.15491897, 12986.42782376,  7708.46421049,
        4076.84240386,  3977.11243373, 13250.36862331, 14829.15491897,
           0.        ,  7118.26461695, 18231.69102728, 15130.71907549,
       15712.80605172, 15116.1820829 , 12986.42782376,  7118.26461695,
           0.        , 16242.84478079, 12389.5922458 , 13028.63271817,
       14231.19211889,  7708.46421049, 18231.69102728, 16242.84478079,
           0.        ,  9044.31104928,  8114.73716577, 13453.91952204,
        4076.84240386, 15130.71907549, 12389.5922458 ,  9044.31104928,
           0.        ,  4089.15431973, 14362.97202891,  3977.11243373,
       15712.80605172, 13028.63271817,  8114.73716577,  4089.15431973,
      

In [ ]:
array([    0.        , 14829.15491897, 12986.42782376,  7708.46421049,
        4076.84240386,  3977.11243373, 13250.36862331, 10983.17121063,
       14892.54574511, 14299.77810531, 10760.00334833, 11289.04306081,
       10722.38032688, 14520.56983296, 14829.15491897,     0.        ,
           0.        , 14829.15491897, 12986.42782376,  7708.46421049,
        4076.84240386,  3977.11243373, 13250.36862331, 14829.15491897,
           0.        ,  7118.26461695, 18231.69102728, 15130.71907549,
       15712.80605172, 15116.1820829 , 12986.42782376,  7118.26461695,
           0.        , 16242.84478079, 12389.5922458 , 13028.63271817,
       14231.19211889,  7708.46421049, 18231.69102728, 16242.84478079,
           0.        ,  9044.31104928,  8114.73716577, 13453.91952204,
        4076.84240386, 15130.71907549, 12389.5922458 ,  9044.31104928,
           0.        ,  4089.15431973, 14362.97202891,  3977.11243373,
       15712.80605172, 13028.63271817,  8114.73716577,  4089.15431973,
           0.        , 13599.61402047, 13250.36862331, 15116.1820829 ,
       14231.19211889, 13453.91952204, 14362.97202891, 13599.61402047,
           0.        ])

In [ ]:
results1 = []
for i in acc_lye:
  for j in acc_lye:
    euclidean_distance =  lambda i,j: np.linalg.norm(i-j)
    d, cost_matrix, acc_cost_matrix, path = dtw(i, j, dist = euclidean_distance)
    results1.append(d)

np.hstack(results1)


array([    0.        , 15470.15069445,  9635.83886849, 10975.85176031,
        3103.85770831,  7033.99649456,  9117.51836155, 15470.15069445,
           0.        , 13666.20012   , 18043.50200591, 14005.59348752,
       17610.54798477, 12355.45566421,  9635.83886849, 13666.20012   ,
           0.        , 11954.82799191,  8837.85382706,  7308.71788802,
       14980.02634949, 10975.85176031, 18043.50200591, 11954.82799191,
           0.        , 11635.57755591,  7099.3992894 , 16703.00187272,
        3103.85770831, 14005.59348752,  8837.85382706, 11635.57755591,
           0.        ,  7321.51868871,  8544.0977147 ,  7033.99649456,
       17610.54798477,  7308.71788802,  7099.3992894 ,  7321.51868871,
           0.        , 14692.71693826,  9117.51836155, 12355.45566421,
       14980.02634949, 16703.00187272,  8544.0977147 , 14692.71693826,
           0.        ])

In [ ]:
array([    0.        , 15470.15069445,  9635.83886849, 10975.85176031,
        3103.85770831,  7033.99649456,  9117.51836155, 15470.15069445,
           0.        , 13666.20012   , 18043.50200591, 14005.59348752,
       17610.54798477, 12355.45566421,  9635.83886849, 13666.20012   ,
           0.        , 11954.82799191,  8837.85382706,  7308.71788802,
       14980.02634949, 10975.85176031, 18043.50200591, 11954.82799191,
           0.        , 11635.57755591,  7099.3992894 , 16703.00187272,
        3103.85770831, 14005.59348752,  8837.85382706, 11635.57755591,
           0.        ,  7321.51868871,  8544.0977147 ,  7033.99649456,
       17610.54798477,  7308.71788802,  7099.3992894 ,  7321.51868871,
           0.        , 14692.71693826,  9117.51836155, 12355.45566421,
       14980.02634949, 16703.00187272,  8544.0977147 , 14692.71693826,
           0.        ])

In [10]:
results3 = []
for i in acc_stand:
  for j in acc_stand:
    euclidean_distance =  lambda i,j: np.linalg.norm(i-j)
    d, cost_matrix, acc_cost_matrix, path = dtw(i, j, dist = euclidean_distance)
    results3.append(d)

np.hstack(results3)

array([    0.        , 16569.97633088, 13925.13694733,  3157.52408422,
        1975.92219426,  1975.92219426, 12691.39775829, 16569.97633088,
           0.        ,  4110.09703947, 15270.06995945, 15848.77288845,
       15848.77288845, 19558.651424  , 13925.13694733,  4110.09703947,
           0.        , 12534.19506047, 12809.44720526, 12809.44720526,
       19299.65087072,  3157.52408422, 15270.06995945, 12534.19506047,
           0.        ,  2449.11175123,  2449.11175123, 14920.08833654,
        1975.92219426, 15848.77288845, 12809.44720526,  2449.11175123,
           0.        ,     0.        , 14296.094205  ,  1975.92219426,
       15848.77288845, 12809.44720526,  2449.11175123,     0.        ,
           0.        , 14296.094205  , 12691.39775829, 19558.651424  ,
       19299.65087072, 14920.08833654, 14296.094205  , 14296.094205  ,
           0.        ])

In [ ]:
array([    0.        , 16569.97633088, 13925.13694733,  3157.52408422,
        1975.92219426,  1975.92219426, 12691.39775829, 16569.97633088,
           0.        ,  4110.09703947, 15270.06995945, 15848.77288845,
       15848.77288845, 19558.651424  , 13925.13694733,  4110.09703947,
           0.        , 12534.19506047, 12809.44720526, 12809.44720526,
       19299.65087072,  3157.52408422, 15270.06995945, 12534.19506047,
           0.        ,  2449.11175123,  2449.11175123, 14920.08833654,
        1975.92219426, 15848.77288845, 12809.44720526,  2449.11175123,
           0.        ,     0.        , 14296.094205  ,  1975.92219426,
       15848.77288845, 12809.44720526,  2449.11175123,     0.        ,
           0.        , 14296.094205  , 12691.39775829, 19558.651424  ,
       19299.65087072, 14920.08833654, 14296.094205  , 14296.094205  ,
           0.        ])

In [ ]:
results = []
for i in acc_jump:
  for j in acc_jump:
    euclidean_distance =  lambda i,j: np.linalg.norm(i-j)
    d, cost_matrix, acc_cost_matrix, path = dtw(i, j, dist = euclidean_distance)
    results.append(d)

np.hstack(results)